apiVersion: v1
kind: Secret
metadata:
  name: fastfood-order-api
  namespace: fiap
type: Opaque
data:
  MongoConnectionString: "bW9uZ29kYjovL2Zhc3Rmb29kdXNlcjpmNHNUZjAwZFA0c3NXMHJkIUBmYXN0Zm9vZC1tb25nbzoyNzAxNy9mYXN0Zm9vZA=="
  